name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dao_generator_annotation:
    path: ../annotation/
  dao_generator_sqlite:
    path: ../sqlite/

  cupertino_icons: ^0.1.2
  package_info: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.0.0
  dao_generator:
    path: ../generator/

flutter:
  uses-material-design: true
