name: dao_generator_sqlite
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.0.0

dev_dependencies:

flutter:
